### ISSUE TITLE
Bloggify link broken

### ISSUE THREAD

**Issue by spences10** [IonicaBizau/ionicabizau.net#32]
I the footer there's a " :heart: from Romania. Powered by [Bloggify.](http://bloggify.github.com/) the link appears to be broken. I looked through the project but couldn't find it hard coded anywhere

![image](https://cloud.githubusercontent.com/assets/234708/21546887/556fe0ba-cdda-11e6-90f1-8b74c4a03f50.png)

**Comment by IonicaBizau** [comment]
Thanks for that! 👍 

It's going to be fixed. I've just published https://bloggify.github.io/ to do a redirection, but seems that something is cached there. I wrote to GitHub Support and waiting for them to clear the cache.

**Comment by IonicaBizau** [comment]
Cache is gone and the redirect works. :tada:
